### ISSUE TITLE
Consuming the API in web browser environment

### ISSUE THREAD

**Issue by patarapolw** [hmil/rest.ts#13]
So far, the [Quick Start](https://github.com/hmil/rest.ts/wiki/Quick-Start) doesn't consider how [consuming the API](https://github.com/hmil/rest.ts/wiki/Quick-Start#4-consume-the-api) in web browser environment would work.

I wrote an example repo just for this, though. -- https://github.com/patarapolw/web-api-typescript-monorepo

Along the way, I met a couple of problems,

- `"skipLibCheck": true` has to be enabled in `tsconfig.json`, as there is this problem
  - Might be able to fix with pinning `"typescript": VERSION` in your `package.json`, just like RESTyped.

```
../../node_modules/runtypes/lib/reflect.d.ts:60:33 - error TS2344: Type 'Runtype<never>' does not satisfy the constraint 'Runtype<any>'.
  The types returned by 'Or(...).match(...)' are incompatible between these types.
    Type 'Matcher2<Runtype<never>, any, Z>' is not assignable to type 'Matcher2<Runtype<any>, any, Z>'.
      Type 'Runtype<any>' is not assignable to type 'Runtype<never>'.

60     constraint: ConstraintCheck<Runtype<never>>;
                                   ~~~~~~~~~~~~~~


Found 1 error.
```

- Axios's CORS is much more problematic than XMLHttpRequest's CORS. It was problem especially when [express cors](https://www.npmjs.com/package/cors) cannot enable CORS. Fixed with

```
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', `http://localhost:${process.env.DEV_SERVER_PORT || '8080'}`)
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE')
  res.header('Access-Control-Allow-Headers', 'Content-Type')
  next()
})
```

**Comment by hmil** [comment]
Thanks for your interest.

I haven't looked at this project in a while, but you raise good points which I think are easy to fix.

## skipLibCheck

I believe this is a bug in runtypes itself which has nothing to do with rest.ts. However, rest.ts depends on an old version of runtypes (2.x vs current version is 4.0.3). So the easy fix could be to just upgrade the dependency.

## cors

I'll add your contribution to the wiki 👍

**Comment by hmil** [comment]
Try with `v0.6.0`, should solve the runtypes/skipLibCheck issue.

**Comment by hmil** [comment]
Closing this as I believe your concerns were addressed.
