### ISSUE TITLE
Routes that don't have a response body are not handled correctly

### ISSUE THREAD

**Issue by erikhofer** [hmil/rest.ts#6]
If you have a route with no `response()` or `response(rt.Void)`, you have to manually call `res.sendStatus(200)`. Otherwise the route doesn't work. Or am I missing something?

**Comment by hmil** [comment]
You always wanna return something. It could be an empty string for instance.

The drawback with Promise-based handlers is that there isn't a clear way to say "propagate the call down the handler chain", as one usually does with express' `next` callback.

So this module won't terminate the request if you return `undefined`. Instead, it propagates the call down the handlers chain.

**Comment by hmil** [comment]
Or, as you've noticed, you can manually terminate the handling by using methods of the `response` object. Note that you'll lose type safety if you chose to do so.

**Comment by erikhofer** [comment]
Ah, okay. Thanks for the clarification.

**Comment by erikhofer** [comment]
Would be nice to add this to the documentation in #4
